services:
# ================= Download Services ==================
  jackett:
    image: linuxserver/jackett
    container_name: media_jackett
    environment:
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ./jackett:/config
      - ${MEDIA_DIR}/jackett/downloads:/downloads
#    ports:
#      - "9117:9117"
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: media_flaresolverr
    environment:
      - TZ=${TZ}
#    ports:
#      - "8191:8191"
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn
    container_name: media_transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./protonvpn/:/etc/openvpn/custom/
      - ./transmission:/config
      - ${MEDIA_DIR}/downloads/completed:/data/completed
      - ${MEDIA_DIR}/downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=${PROTONVPN_NODE}.protonvpn.udp
      - OPENVPN_USERNAME=${PROTONVPN_USERNAME}+pmp
      - OPENVPN_PASSWORD=${PROTONVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.1.0/24
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-size: 10m
    dns:
      - 1.1.1.1
      - 1.1.0.0
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
    #  - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"

# ================= Media Management Services ==================
  # jellyfin:
  # Because we run Jellyfin on a Mac M2, it is advised to download the application directly
  # from the website and run it directly, as the Docker image is not supported.

  sonarr:
    image: linuxserver/sonarr
    container_name: media_sonarr
    environment:
      - TZ=${TZ}
    volumes:
      - ./sonarr_config:/config
      - ${MEDIA_DIR}/anime:/anime
      - ${MEDIA_DIR}/tvshows:/tvshows
      - ${MEDIA_DIR}/downloads/completed:/data/completed
#    ports:
#      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: media_radarr
    environment:
      - TZ=${TZ}
    volumes:
      - ./radarr_config:/config
      - ${MEDIA_DIR}/downloads/completed:/data/completed
      - ${MEDIA_DIR}/movies:/movies
#    ports:
#      - "7878:7878"
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: media_bazarr
    environment:
      - TZ=${TZ}
    volumes:
      - ./bazarr_config:/config
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/tvshows:/tvshows
      - ${MEDIA_DIR}/anime:/anime
#    ports:
#      - "6767:6767"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: media_jellyseerr
    environment:
      - TZ=${TZ}
#    ports:
#      - "5055:5055"
    volumes:
      - ./jellyseerr_config:/app/config
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
